apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-eureka-auth-pod
  labels:
    name: spring-eureka-auth
  namespace: spring-cloud
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: spring-eureka-auth
    spec:
      containers:
      - name: spring-eureka-auth
        image: spring-eureka-auth:v1
        env:
        - name: EUREKA_SERVER
          value: eureka-server.spring-cloud.svc.cluster.local
        - name: _JAVA_OPTIONS
          value: -Deureka.instance.preferIpAddress=false -Deureka.client.serviceUrl.defaultZone=http://eureka-server.spring-cloud.svc.cluster.local:8761/eureka/
        ports:
        - containerPort: 9100
---
apiVersion: v1
kind: Service
metadata:
  name: spring-eureka-auth
  labels: 
    name: spring-eureka-auth
  namespace: spring-cloud
spec:
  type: NodePort
  ports:
  - port: 9100
    targetPort: 9100
  selector:
    name: spring-eureka-auth