apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: currency-conversion-service-pod
  labels:
    name: currency-conversion-service
  namespace: spring-cloud
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: currency-conversion-service
    spec:
      containers:
      - name: currency-conversion-service
        image: currency-conversion-service:v1
        env:
        - name: _JAVA_OPTIONS
          value: -Dcurrency-exchange-service.ribbon.listOfServers=http://currency-exchange-service:8000 -Deureka.instance.preferIpAddress=false -Deureka.client.serviceUrl.defaultZone=http://eureka-server.spring-cloud.svc.cluster.local:8761/eureka/
        - name: RABBIT_URI
          value: amqp://rabbitmq
        ports:
        - containerPort: 8100
---
apiVersion: v1
kind: Service
metadata:
  name: currency-conversion-service
  labels: 
    name: currency-conversion-service
  namespace: spring-cloud
spec:
  type: NodePort
  ports:
  - port: 8100
    targetPort: 8100
  selector:
    name: currency-conversion-service