apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-broker0
spec:
  template:
    metadata:
      labels:
        app: kafka
        id: "0"
    spec:
      containers:
      - name: kafka
        image: kafka:2.12-2.3.0
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT_HOST
          value: zoo1
        ports:
        - containerPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    name: kafka
spec:
  ports:
  - port: 9092
    name: kafka-port
    targetPort: 9092
  selector:
    app: kafka
    id: "0"
  type: NodePort