apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
  namespace: spring-cloud
  labels:
    name: kafka-broker
spec:
  ports:
  - port: 9092
    targetPort: 9092
  selector:
    name: kafka-broker