apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-broker1
spec:
  template:
    metadata:
      labels:
        app: kafka
        id: "1"
    spec:
      containers:
      - name: kafka
        image: kafka:2.12-2.3.0
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT_HOST
          value: zoo1
        - name: KAFKA_ZOOKEEPER_CONNECT_PORT
          value: "2181"
        - name: KAFKA_BROKER_ID
          value: "1"
        ports:
        - containerPort: 9092