apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
  namespace: spring-cloud
  labels:
    name: kafka-broker
spec:
  ports:
  - port: 9092
    name: kafka-port
    protocol: TCP
  selector:
    name: kafka-broker
  type: LoadBalancer