apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-broker
  labels:
    name: kafka-broker
  namespace: spring-cloud
spec:
  serviceName: kafka-broker
  replicas: 1
  selector:
    matchLabels:
      name: kafka-broker
  template:
    metadata:
      labels:
        name: kafka-broker
    spec:
      containers:
      - name: kafka-broker
        image: kafka:v1
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT_HOST
          value: zoo1.default.svc.cluster.local
        - name: KAFKA_ZOOKEEPER_CONNECT_PORT
          value: "2181"
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_ADVERTISED_HOST
          value: 10.1.3.6
        ports:
        - containerPort: 9092